services:
  bot:
    build: .
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data


networks:
  default:

volumes:
  pgdata: