apiVersion: v1
kind: Service
metadata:
  labels:
    com.github.blahblahbloopster.service: db
  name: postgres
spec:
  ports:
    - port: 5432
      name: "postges"
  selector:
    com.github.blahblahbloopster.service: db
